services:
    php:
        build: phpdocker/php
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php/Caddyfile:/etc/frankenphp/Caddyfile'
            - './phpdocker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        ports:
            - '30000:80'
