services:
    php:
        build: docker
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/Caddyfile:/etc/frankenphp/Caddyfile'
            - './docker/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
        ports:
            - '30000:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
